name: Documentation Issue
description: Report issues or suggest improvements to documentation
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve REAPER's documentation!

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation is this about?
      options:
        - Getting Started Guide
        - API Reference
        - Plugin Development Guide
        - Operator Console Guide
        - Sense Isolation FAQ
        - Architecture/Philosophy
        - Examples
        - README
        - Code Comments
        - Other
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What kind of documentation issue is this?
      options:
        - Incorrect information
        - Missing information
        - Unclear/confusing explanation
        - Typo or grammar issue
        - Broken link
        - Missing example
        - Outdated content
        - Suggestion for improvement
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Document Location
      description: Where is this documentation located?
      placeholder: public_docs/how-to-create-plugins.md (line 42)
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: What's wrong or missing?
      placeholder: The documentation says X, but actually Y happens...
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Fix or Improvement
      description: How would you fix or improve this?
      placeholder: |
        Change:
        "Old text..."
        
        To:
        "New text..."
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any additional context or related documentation
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to submit a PR to fix this
