name: ✨ Feature Request
description: Suggest a new feature for REAPER (non-plugin)
title: "[Feature]: "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! For plugin-specific requests, please use the "Plugin Request" template.
  
  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - Core Framework Enhancement
        - Plugin Manager Improvement
        - Data Model Extension
        - Testing Infrastructure
        - Documentation
        - Developer Tools
        - Other
    validations:
      required: true
  
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the problem or limitation you're experiencing
    validations:
      required: true
  
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: Describe your ideal solution
    validations:
      required: true
  
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches have you considered?
      placeholder: Describe alternative solutions you've thought about
  
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low (nice to have)
        - Medium (would improve workflow)
        - High (blocking current work)
    validations:
      required: true
  
  - type: checkboxes
    id: breaking-change
    attributes:
      label: Breaking Change
      description: Would this be a breaking change?
      options:
        - label: This would be a breaking change
        - label: This is backward compatible
  
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information (code examples, mockups, etc.)
