name: Feature Request
description: Suggest a new feature or enhancement for REAPER
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I would like REAPER to...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area does this feature relate to?
      options:
        - New Plugin (detection, scoring, action)
        - Core Framework Enhancement
        - Pipeline Improvement
        - Developer Experience
        - Documentation
        - Testing/Quality
        - Automation
        - Other
    validations:
      required: true

  - type: dropdown
    id: phase
    attributes:
      label: Roadmap Phase
      description: Which phase of the roadmap does this align with?
      options:
        - Phase 1 - Core Architecture (Alpha)
        - Phase 2 - Pipeline Completion (Beta)
        - Phase 3 - Learning & Operator Experience
        - Phase 4 - Quality, Automation, Community
        - Future/Post-v1.0
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternative solutions or features you've considered

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to ensure this isn't a duplicate
          required: true
        - label: This feature aligns with REAPER's core principles (plugin-driven, type-safe, separation of concerns)
          required: true
